[[rules]]
name="test"
pattern="src/**/*.test.ts"

[[rules.links]]
name="src"
pattern="src/{$*}.ts"

[[rules]]
name="lib"
pattern="src/**/*.ts"
template='''
export default function {$*} () {
  return "helloworld"
}
'''

[[rules.links]]
name="test"
pattern="src/{$*}.test.ts"
