[[rules]]
name="test"
pattern="src/**/*.test.ts"

[[rules.links]]
name="src"
pattern="src/{$1}.ts"

[[rules]]
name="lib"
pattern="src/**/*.ts"
template='''
export default function helloworld() {
  return "helloworld"
}
'''

[[rules.links]]
name="test"
pattern="src/{$1}.test.ts"
