// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Path from "path";
import * as Projet from "./projet";

function findRule(prim, prim$1) {
  return Projet.getRule(prim, prim$1);
}

function list(config, ruleName) {
  var rule = Projet.getRule(config, ruleName);
  if (rule !== undefined) {
    return Path.dirname(config.path);
  } else {
    return "no_rule";
  }
}

export {
  findRule ,
  list ,
  
}
/* path Not a pure module */
